### ISSUE TITLE
TC blocks calculated in a wrong way?

### ISSUE THREAD

**Issue by leodmel** [eambutu/snail-pytorch#2]
I guess the code in the file `blocks.py`
```
int(math.ceil(math.log(seq_length)))
```
is wrong? Because `math.log(x)` return the natural logarithm of x, and I suppose we want a base-2 logarithm of x here?

**Comment by eambutu** [comment]
Wow you're right, that's a pretty big bug. Pushing a fix out right now. Unfortunately, I don't have access to compute resources for the time being, so I'm unable to rerun the numbers though.

**Comment by leodmel** [comment]
That's alright 👍
